version: '3.8'

services:
  ad-data-app:
    build: .
    container_name: ad-data-aggregator
    restart: unless-stopped
    ports:
      - "3300:8080"
    environment:
      # 时区设置
      TZ: Asia/Shanghai
      
      # 源数据库配置（生产环境请修改）
      SOURCE_DB_HOST: ${SOURCE_DB_HOST:-103.36.221.200}
      SOURCE_DB_PORT: ${SOURCE_DB_PORT:-3316}
      SOURCE_DB_USER: ${SOURCE_DB_USER:-root}
      SOURCE_DB_PASSWORD: ${SOURCE_DB_PASSWORD:-Yyy443556.0}
      SOURCE_DB_DATABASE: ${SOURCE_DB_DATABASE:-ad_router}
      SOURCE_TABLE_NAME: ${SOURCE_TABLE_NAME:-request_log}
      
      # 目标数据库配置（连接外部MySQL）
      TARGET_DB_HOST: ${TARGET_DB_HOST:-103.36.221.200}
      TARGET_DB_PORT: ${TARGET_DB_PORT:-3316}
      TARGET_DB_USER: ${TARGET_DB_USER:-root}
      TARGET_DB_PASSWORD: ${TARGET_DB_PASSWORD:-Yyy443556.0}
      TARGET_DB_DATABASE: ${TARGET_DB_DATABASE:-ad_data}
      
      # Flask应用配置
      FLASK_HOST: ${FLASK_HOST:-0.0.0.0}
      FLASK_PORT: ${FLASK_PORT:-8080}
      FLASK_DEBUG: ${FLASK_DEBUG:-false}
    volumes:
      # 挂载日志目录到宿主机
      - ./logs:/app/logs
      # 挂载归档目录到宿主机指定位置
      - /data/ad/archives:/app/data_archive/archives
      - /data/ad/logs:/app/data_archive/logs
      # 挂载时区文件确保时区设置正确
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/filter-options"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ad-data-network

networks:
  ad-data-network:
    driver: bridge
